In [3]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [9]:
df = pd.read_csv('titanic_toy.csv')

In [10]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [12]:
df.isnull().sum()

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [13]:
imputer = IterativeImputer(estimator=LinearRegression(),max_iter=50)

In [14]:
df_new = imputer.fit_transform(df)

In [15]:
df = pd.DataFrame(df_new,columns=df.columns)

In [17]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500     1.0       0.0
1  38.0  71.2833     1.0       1.0
2  26.0   7.9250     0.0       1.0
3  35.0  53.1000     1.0       1.0
4  35.0   8.0500     0.0       0.0

In [18]:
df.isnull().sum()

Age         0
Fare        0
Family      0
Survived    0
dtype: int64

In [ ]:
# we can see that we filled all the missing values using iterative imputer