In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('titanic_toy.csv',usecols=['Age','Fare','Survived'])

In [5]:
df.head()

    Age     Fare  Survived
0  22.0   7.2500         0
1  38.0  71.2833         1
2  26.0   7.9250         1
3  35.0  53.1000         1
4  35.0   8.0500         0

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator

In [7]:
x_train , x_test , y_train , y_test = train_test_split(df.iloc[:,0:2],df['Survived'],test_size=0.2,random_state=245)

In [16]:
mis = MissingIndicator()
x_train.head()

      Age     Fare
19    NaN   7.2250
274   NaN   7.7500
475   NaN  52.0000
598   NaN   7.2250
833  23.0   7.8542

In [18]:
x_train_age = mis.fit_transform(x_train.iloc[:,0:1])

In [19]:
x_test_age = mis.transform(x_test.iloc[:,0:1])

In [20]:
x_train['age indicator'] = x_train_age

In [21]:
x_test['age indicator'] = x_test_age

In [22]:
x_train.head()

      Age     Fare  age indicator
19    NaN   7.2250           True
274   NaN   7.7500           True
475   NaN  52.0000           True
598   NaN   7.2250           True
833  23.0   7.8542          False

In [ ]:
 # we will do automatic parameter finding when we will start learning models