In [1]:
# pandas is the most useful library that is used to work with data
import pandas as pd

In [3]:
# we can import data from our system locally
df = pd.read_csv('train_and_test2.csv')
df.head(5)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [8]:
# sep parameter is used so we can seperate values with any other thing than tsv
# here for example i have a tsv dataset 
pd.read_csv('TSV.tsv',sep ='\t')
# i have to set sep parameter as \t so that it can read tsv files

   StudentID      Name  Age  Course  Marks
0        101     Alice   20      ML     85
1        102       Bob   21     DSA     78
2        103   Charlie   19      ML     92
3        104     David   22  WebDev     74
4        105      Emma   20     DSA     88
5        106     Frank   21      ML     81
6        107     Grace   19  WebDev     95
7        108     Henry   22     DSA     69
8        109  Isabella   20      ML     90
9        110      Jack   21  WebDev     76

In [18]:
# if i don't have any name of our collumns we can pass a list of names so that we can easily setup names for our collumns
pd.read_csv('TSV.tsv',sep='\t',names = ['ID','Name','Age','Subject','Numbers']).iloc[1:,:]
# as you can see i removed the original collumn and set it by myself

     ID      Name Age Subject Numbers
1   101     Alice  20      ML      85
2   102       Bob  21     DSA      78
3   103   Charlie  19      ML      92
4   104     David  22  WebDev      74
5   105      Emma  20     DSA      88
6   106     Frank  21      ML      81
7   107     Grace  19  WebDev      95
8   108     Henry  22     DSA      69
9   109  Isabella  20      ML      90
10  110      Jack  21  WebDev      76

In [20]:
# we can set index collumn to any other collumm 
pd.read_csv('TSV.tsv',sep = '\t',index_col='StudentID')

               Name  Age  Course  Marks
StudentID
101           Alice   20      ML     85
102             Bob   21     DSA     78
103         Charlie   19      ML     92
104           David   22  WebDev     74
105            Emma   20     DSA     88
106           Frank   21      ML     81
107           Grace   19  WebDev     95
108           Henry   22     DSA     69
109        Isabella   20      ML     90
110            Jack   21  WebDev     76

In [25]:
# if i dont want first 5 rows i  can use the header parameter 
pd.read_csv('train_and_test2.csv',header=6)

,6,28,8.4583,0,0.1,0.2,0.3,0.4,0.5,0.6,...,0.15,0.16,0.17,3,0.18,0.19,1,0.20,0.21,0.22
0,7,54.0,51.8625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,0
1,8,2.0,21.0750,0,3,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
2,9,27.0,11.1333,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,10,14.0,30.0708,1,1,0,0,0,0,0,...,0,0,0,2,0,0,0.0,0,0,1
4,11,4.0,16.7000,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1299,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1300,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1301,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1302,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [34]:
# i want only hours studied and marks so i can use usecols to select cols
pd.read_csv('Students.csv',usecols = ['StudentID','Hours_Studied','Marks'],index_col='StudentID')

           Hours_Studied  Marks
StudentID
1                      2     45
2                      3     50
3                      4     55
4                      5     60
5                      6     65
...                  ...    ...
96                     9     87
97                     2     58
98                     3     63
99                     4     68
100                    5     73

[100 rows x 2 columns]

In [38]:
# if we want to skip some rows or want some particular rows we can use this function
pd.read_csv('Students.csv',skiprows=[0,1,2,4,5,6,7,8,9,10])

      3  20  4  70  55
0    11  21  4  90  62
1    12  22  5  92  67
2    13  23  6  94  72
3    14  24  7  96  77
4    15  18  8  98  82
..  ...  .. ..  ..  ..
85   96  22  9  74  87
86   97  23  2  76  58
87   98  24  3  79  63
88   99  18  4  82  68
89  100  19  5  85  73

[90 rows x 5 columns]

In [41]:
# if we want less data we can use nrows so that we select only the rows we want 
pd.read_csv('Students.csv',nrows = 10)

   StudentID  Age  Hours_Studied  Attendance  Marks
0          1   18              2          65     45
1          2   19              3          68     50
2          3   20              4          70     55
3          4   21              5          72     60
4          5   22              6          75     65
5          6   23              7          78     70
6          7   24              8          80     75
7          8   18              9          82     80
8          9   19              2          85     52
9         10   20              3          88     58

In [44]:
# to skip the bad lines
pd.read_csv('Students.csv',on_bad_lines='skip')

    StudentID  Age  Hours_Studied  Attendance  Marks
0           1   18              2          65     45
1           2   19              3          68     50
2           3   20              4          70     55
3           4   21              5          72     60
4           5   22              6          75     65
..        ...  ...            ...         ...    ...
95         96   22              9          74     87
96         97   23              2          76     58
97         98   24              3          79     63
98         99   18              4          82     68
99        100   19              5          85     73

[100 rows x 5 columns]

In [46]:
# we can use dtype function to change the datatype of the features
pd.read_csv('Students.csv',dtype={'Marks':float,'Attendance':float})

    StudentID  Age  Hours_Studied  Attendance  Marks
0           1   18              2        65.0   45.0
1           2   19              3        68.0   50.0
2           3   20              4        70.0   55.0
3           4   21              5        72.0   60.0
4           5   22              6        75.0   65.0
..        ...  ...            ...         ...    ...
95         96   22              9        74.0   87.0
96         97   23              2        76.0   58.0
97         98   24              3        79.0   63.0
98         99   18              4        82.0   68.0
99        100   19              5        85.0   73.0

[100 rows x 5 columns]

In [53]:
# we can use parse_dates to set a collumn as dates collumn
pd.read_csv('C:/Skills/Machine Learning/Pandas/IPL MATCHES.csv',parse_dates=['date'])

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [66]:
# we can use converters which will pass a function and the collumn that we want to apply the function on
def debar(att):
    att = int(att) 
    if att>=75:
        return att
    else:
        return "Debared"
pd.read_csv('Students.csv',converters={'Attendance':debar})

    StudentID  Age  Hours_Studied Attendance  Marks
0           1   18              2    Debared     45
1           2   19              3    Debared     50
2           3   20              4    Debared     55
3           4   21              5    Debared     60
4           5   22              6         75     65
..        ...  ...            ...        ...    ...
95         96   22              9    Debared     87
96         97   23              2         76     58
97         98   24              3         79     63
98         99   18              4         82     68
99        100   19              5         85     73

[100 rows x 5 columns]

In [76]:
# example we dont need the data of 75 so what we can do is 
pd.read_csv('Students.csv',na_values=[75] )

    StudentID  Age  Hours_Studied  Attendance  Marks
0         1.0   18              2        65.0   45.0
1         2.0   19              3        68.0   50.0
2         3.0   20              4        70.0   55.0
3         4.0   21              5        72.0   60.0
4         5.0   22              6         NaN   65.0
..        ...  ...            ...         ...    ...
95       96.0   22              9        74.0   87.0
96       97.0   23              2        76.0   58.0
97       98.0   24              3        79.0   63.0
98       99.0   18              4        82.0   68.0
99      100.0   19              5        85.0   73.0

[100 rows x 5 columns]

In [87]:
# loading huge dataset in chunks
pd.read_csv('train_and_test2.csv')#there are 1308 rows 
dfs = pd.read_csv('train_and_test2.csv',chunksize=300)
for meow in dfs:
    print(meow)
# we can use for loops to acess the data divided in chunks

In [ ]:
# this was all about handling csv files