In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('PandasPractice.csv')

In [6]:
# first five rows 
df.head()

   id      name  age  math  science  english  attendance
0   1  Student1   20    57       43       98          85
1   2  Student2   21    65       69       56          98
2   3  Student3   18    83       76       77          78
3   4  Student4   20    73       62       63          73
4   5  Student5   20    49       78       44          70

In [7]:
# last 5 rows 
df.tail()

     id        name  age  math  science  english  attendance
95   96   Student96   19    78       94       85          71
96   97   Student97   19    88       43       57          95
97   98   Student98   21    91       94       41          86
98   99   Student99   19   100       50       93          77
99  100  Student100   18    71       95       74          70

In [8]:
# to find the shape of object 
df.shape

(100, 7)

In [9]:
# `
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    int64
 1   name        100 non-null    object
 2   age         100 non-null    int64
 3   math        100 non-null    int64
 4   science     100 non-null    int64
 5   english     100 non-null    int64
 6   attendance  100 non-null    int64
dtypes: int64(6), object(1)
memory usage: 5.6+ KB

In [13]:
# we can see there are no missing values 
nd = df.values
nd[0,3]=np.nan

In [25]:
# used to convert nd array into dataframe
df = pd.DataFrame(nd)

In [30]:
df = df.dropna()

In [38]:
df = df.drop_duplicates()
df

      0           1   2    3   4   5   6
1     2    Student2  21   65  69  56  98
2     3    Student3  18   83  76  77  78
3     4    Student4  20   73  62  63  73
4     5    Student5  20   49  78  44  70
5     6    Student6  21   75  84  91  73
..  ...         ...  ..  ...  ..  ..  ..
95   96   Student96  19   78  94  85  71
96   97   Student97  19   88  43  57  95
97   98   Student98  21   91  94  41  86
98   99   Student99  19  100  50  93  77
99  100  Student100  18   71  95  74  70

[99 rows x 7 columns]

In [41]:
df = df.rename(columns={0:'ID',1:'name',2:'age',3:'math',4:'science',5:'english',6:'attendance'})
df

     ID        name age math science english attendance
1     2    Student2  21   65      69      56         98
2     3    Student3  18   83      76      77         78
3     4    Student4  20   73      62      63         73
4     5    Student5  20   49      78      44         70
5     6    Student6  21   75      84      91         73
..  ...         ...  ..  ...     ...     ...        ...
95   96   Student96  19   78      94      85         71
96   97   Student97  19   88      43      57         95
97   98   Student98  21   91      94      41         86
98   99   Student99  19  100      50      93         77
99  100  Student100  18   71      95      74         70

[99 rows x 7 columns]

In [44]:
# filtering 
# student with only maths marks >80
df = df[df['math']>80]
df

    ID       name age math science english attendance
2    3   Student3  18   83      76      77         78
8    9   Student9  20   87      68      61         90
13  14  Student14  20   99      98      48         76
14  15  Student15  21   96      90      99         72
18  19  Student19  21   84      81      68         81
20  21  Student21  19   86      96      59         88
21  22  Student22  18   92      92      99         91
25  26  Student26  19   99      83      65         99
26  27  Student27  19   99      83      42         75
27  28  Student28  19   99      59      58         75
28  29  Student29  21   84      69      59         82
32  33  Student33  21   84      67      80         96
39  40  Student40  20   83      96      50         84
43  44  Student44  21   90      42      89         98
49  50  Student50  19   98      76      46         86
51  52  Student52  19   81      90      55         97
53  54  Student54  21   97      83      87         98
62  63  Student63  18   87      91      44         98
63  64  Student64  18   94      88      76         86
68  69  Student69  21   83      78      80         97
76  77  Student77  21   86      98      93         72
82  83  Student83  18   94      62      88         95
90  91  Student91  21   81      83      64         92
91  92  Student92  21   99      65      74         71
93  94  Student94  19   90      45      68         96
96  97  Student97  19   88      43      57         95
97  98  Student98  21   91      94      41         86
98  99  Student99  19  100      50      93         77

In [47]:
# df where attendance is 90+
df = df[df['attendance']>90]
df

    ID       name age math science english attendance
21  22  Student22  18   92      92      99         91
25  26  Student26  19   99      83      65         99
32  33  Student33  21   84      67      80         96
43  44  Student44  21   90      42      89         98
51  52  Student52  19   81      90      55         97
53  54  Student54  21   97      83      87         98
62  63  Student63  18   87      91      44         98
68  69  Student69  21   83      78      80         97
82  83  Student83  18   94      62      88         95
90  91  Student91  21   81      83      64         92
93  94  Student94  19   90      45      68         96
96  97  Student97  19   88      43      57         95

In [50]:
# student aged 19
df= df [df['age']==19]
df

    ID       name age math science english attendance
25  26  Student26  19   99      83      65         99
51  52  Student52  19   81      90      55         97
93  94  Student94  19   90      45      68         96
96  97  Student97  19   88      43      57         95

In [58]:
# sorting 
# by maths marks 
df.sort_values('math',inplace=True)

In [60]:
# sort by attendance 
df.sort_values('attendance',ascending=False,inplace=True)

In [61]:
df

    ID       name age math science english attendance
25  26  Student26  19   99      83      65         99
51  52  Student52  19   81      90      55         97
93  94  Student94  19   90      45      68         96
96  97  Student97  19   88      43      57         95

In [65]:
df['Total'] = df['math']+df['science']+df['english']

In [69]:
df.drop('grade',axis=1,inplace=True)

In [70]:
df

    ID       name age math science english attendance Total
25  26  Student26  19   99      83      65         99   247
51  52  Student52  19   81      90      55         97   226
93  94  Student94  19   90      45      68         96   203
96  97  Student97  19   88      43      57         95   188

In [71]:
df['percentage'] = (df['Total']/300)*100

In [72]:
df

    ID       name age math science english attendance Total percentage
25  26  Student26  19   99      83      65         99   247  82.333333
51  52  Student52  19   81      90      55         97   226  75.333333
93  94  Student94  19   90      45      68         96   203  67.666667
96  97  Student97  19   88      43      57         95   188  62.666667

In [ ]:
# we will continue practice as required